import type { Metadata } from "next";
import { moderat_medium } from "@/utils/font";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
	icons: "/favicon.jpg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={moderat_medium.className}>{children}</body>
    </html>
  );
}
